
spring:
  datasource:
    url: jdbc:mysql:///seckill
    username: root
    password: 123456
  devtools:
    restart:
      enabled: true # 设置开启热部署
      additional-paths: src/main/java # 重启目录
server:
  port: 8888

#debug: true
logging:
  level:
    me.xcx.seckill.controller: DEBUG
